### ISSUE TITLE
请问这个是新版本python写的嘛？

### ISSUE THREAD

**Issue by C00LMIN** [broholens/coldcalls#1]
有两个需要的库我这里装不上，我的python版本在3.4以下，pip安装获取不到这两个库诶~

**Comment by broholens** [comment]
> 有两个需要的库我这里装不上，我的python版本在3.4以下，pip安装获取不到这两个库诶~

基于python3.8编写。哪些库装不上？

**Comment by C00LMIN** [comment]
你好，多谢回复。
```
C:\Users\59722>pip install loguru
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting loguru
  ERROR: Could not find a version that satisfies the requirement loguru (from versions: none)
ERROR: No matching distribution found for loguru

C:\Users\59722>pip install Faker
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Requirement already satisfied: Faker in c:\python34\lib\site-packages (4.1.1)
Requirement already satisfied: python-dateutil>=2.4 in c:\python34\lib\site-packages (from Faker) (2.8.1)
Requirement already satisfied: text-unidecode==1.3 in c:\python34\lib\site-packages (from Faker) (1.3)
Requirement already satisfied: six>=1.5 in c:\python34\lib\site-packages (from python-dateutil>=2.4->Faker) (1.11.0)

C:\Users\59722>pip install pyfunctions
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting pyfunctions
  ERROR: Could not find a version that satisfies the requirement pyfunctions (from versions: none)
ERROR: No matching distribution found for pyfunctions
```

然后因为我的pip版本只能在python3.4的环境下更新到19.0，如上面命令行的提示~

所以是这个原因吗~测试了应该不是连不上服务器的原因额。只初步学习了python，不太懂，麻烦了

**Comment by broholens** [comment]
> 你好，多谢回复。
> 
> ```
> C:\Users\59722>pip install loguru
> DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
> Collecting loguru
>   ERROR: Could not find a version that satisfies the requirement loguru (from versions: none)
> ERROR: No matching distribution found for loguru
> 
> C:\Users\59722>pip install Faker
> DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
> Requirement already satisfied: Faker in c:\python34\lib\site-packages (4.1.1)
> Requirement already satisfied: python-dateutil>=2.4 in c:\python34\lib\site-packages (from Faker) (2.8.1)
> Requirement already satisfied: text-unidecode==1.3 in c:\python34\lib\site-packages (from Faker) (1.3)
> Requirement already satisfied: six>=1.5 in c:\python34\lib\site-packages (from python-dateutil>=2.4->Faker) (1.11.0)
> 
> C:\Users\59722>pip install pyfunctions
> DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
> Collecting pyfunctions
>   ERROR: Could not find a version that satisfies the requirement pyfunctions (from versions: none)
> ERROR: No matching distribution found for pyfunctions
> ```
> 
> 然后因为我的pip版本只能在python3.4的环境下更新到19.0，如上面命令行的提示~
> 
> 所以是这个原因吗~测试了应该不是连不上服务器的原因额。只初步学习了python，不太懂，麻烦了

https://github.com/Delgan/loguru
loguru支持python3.5+，所以如果条件允许的话，考虑升级一下python版本

**Comment by C00LMIN** [comment]
是的，昨晚自己没事又来调试了一下。发现loguru是3.5以上的版本。目前已经可以跑了，谢谢大佬~
另外发现一个问题：
```

1. http://baiduloushi.com/plus/view.php?aid=653
2. http://zs.jiameng.com/goJmPriceBoard2.html
```
上面这样的接口提交信息后弹出的好像不是alert框，而是：******（网站链接）显示**：提交成功！
像这样的提交之后，后面的site就不能正确使用driver继续打开了，程序就结束了~

**Comment by broholens** [comment]
> ****（网站链接）显示：提交成功！

这个就是一个alert.

另外，下面是我运行的一部分结果，并没有出现程序结束的情况：
>2020-07-14 20:07:04.404 | INFO     | __main__:run:123 - [ERROR] http://baiduloushi.com/plus/view.php?aid=653
>2020-07-14 20:07:35.899 | INFO     | __main__:run:116 - [SUCCESS] http://www.bole.com/registerPage

**Comment by C00LMIN** [comment]
额，就是我用循环的那个跑的话，就会终止了，后面的就无法继续执行了。
但是单独跑它确实没问题，好像不是一个alert吧。不过也可能是我这边的问题吧~

**Comment by xpyqiubai** [comment]
这个感觉比其它的之前比较老的好很多，就是大佬感觉可以把readme写详细一点，比如哪里传参，修改之类的，不过已经很好了

**Comment by broholens** [comment]
> ，后面的就无法继续执行了。
> 但是单独跑它确实没问题，好像不是一个alert吧。不过也可能是

如果有异常导致程序不可运行，可以把这个网站在配置文件中删掉
